name: pull request
# on: pull_request
on: dispatch
env:
  GO_VERSION: "1.16.x"
jobs:
  cancel:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./go/src/github.com/teamwork/teamworkapigen
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # we need the repo history to see what packages changed
          path: go/src/github.com/teamwork/teamworkapigen

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Generate Go Client
        run: bash ./bin/generate_go_client.sh
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GH_USER_NAME: David Hontecillas
          GH_USER_EMAIL: dhontecillas@gmail.com
          GO_CLIENT_BRANCH: ${{ github.ref }}
          CREATE_PR: true
